### ISSUE TITLE
Problem exporting jpg, and layer visibility issue on OSX

### ISSUE THREAD

**Issue by ugajin-nijagu** [jespino/inkscape-export-layers#2]
There is an issue with Inkscape v0.91 on pre-build for OSX 
- Does not export .jpg, and deletes previously exported png files when in .jpg mode

Example: 

I have file with two layers named with [export] prefix and export to .png
- [export] Layer 2
- [export] Layer 1 
  Inkscape exports files and toggles visibility to hide layer 1 - strange one!

If I run extension a second time in .jpg mode, the previously exported .png files are gone!

Thanks.

-u

**Comment by Xaviju** [comment]
> Does not export .jpg, and deletes previously exported png files when in .jpg mode

This is the expected behavior. Inkscape only exports to PNG. The extension uses imagemagick to convert the file to JPEG. If you run it twice with the same name, it overrides the previous files and then deletes the PNG. The extension could be enhanced by adding a property to export both. But, for the moment, you can just change the name of the layers and export again and you will get two different files.

For exporting JPEG, please ensure that you have [imagemagick](http://imagemagick.org/script/index.php) installed. Its a required dependency. I will review the documentation.

**Comment by ugajin-nijagu** [comment]
It will be helpful if you make clear any required dependencies. 
AFAIK OS X pre-build will not usually include image magic, and I won't be installing it.  
Also, I am surprised that two files with identical file names, but different filename extensions should overwrite each other. This is unheard of behaviour on OS X.
In addition, it is't very user friendly, to have to change the layer names in order to export to both formats.
Inkscape may not export, but it does save to other formats, including .xcf.
You do not comment on the layer visibility issue.
Thanks
-u

**Comment by jespino** [comment]
I agree, this behavior must be fixed, is a bit agressive to delete a file without asking. My idea is to generate the png as a temporary filename when exporting to jpeg.

Thanks for your feedback I going to reopen the issue to improve this part as soon as posible.

**Comment by jespino** [comment]
Solved! Thanks again :)
